### ISSUE TITLE
Question: Write/Edit Metadata ?

### ISSUE THREAD

**Issue by boustanihani** [uswriting/exiftool#1]
Thanks for the great work.

Just one question, is it possible to use all ExifTool features, including the ability to write and edit metadata?

If so, could you give a small example of how to do this?

**Comment by andrewmd5** [comment]
If the file is entirely in memory then it should be possible to write to it by calling the same arguments you would with ExifTool on the command line; this library doesn't expose the underlying file system or allow you to pass one in though, so fork and validate  the use case and if it works I'm happily accept a PR.

**Comment by boustanihani** [comment]
Thanks. I will try this and give you some feedback.

Could you just add to the documentation how to install from a CDN like `jsdelivr` & `unpkg` ?

https://www.jsdelivr.com/package/npm/@uswriting/exiftool
https://unpkg.com/

`jsdelivr` is currently throwing the following error => `Failed to bundle using Rollup v2.79.2.` Check:
- https://www.jsdelivr.com/package/npm/@uswriting/exiftool
- https://cdn.jsdelivr.net/npm/@uswriting/exiftool@1.0.1/+esm

**Comment by andrewmd5** [comment]
Ah, looks like that was my fault. I fixed it in 1.0.3 

https://cdn.jsdelivr.net/npm/@uswriting/exiftool@1.0.3/+esm

**Comment by boustanihani** [comment]
Cool, thanks for the quick fix, the static version is working now :)

`Latest Patch` & `Latest Major` are also working, only `Latest Minor` is still throwing this error.

Latest Minor
https://cdn.jsdelivr.net/npm/@uswriting/exiftool@1/+esm
Failed to bundle using Rollup v2.79.2.

Latest Patch
https://cdn.jsdelivr.net/npm/@uswriting/exiftool@1.0/+esm

Latest Major
https://cdn.jsdelivr.net/npm/@uswriting/exiftool/+esm

**Comment by boustanihani** [comment]
> If the file is entirely in memory then it should be possible to write to it by calling the same arguments you would with ExifTool on the command line; this library doesn't expose the underlying file system or allow you to pass one in though, so fork and validate the use case and if it works I'm happily accept a PR.

What do you mean by "If the file is entirely in memory..." ?

I usually use `node` and the package `exiftool-vendored`:
https://github.com/photostructure/exiftool-vendored.js

Say I have some tags I want to write to a file =>

```
var tags = {
  "IPTC:Credit": "...",
  "IPTC:Headline": "...",
  "IPTC:Keywords": "...",
  "XMP-photoshop:Credit": "...",
  "XMP-photoshop:Headline": "...",
  "XMP-dc:Subject": ["..."],
};
```

I use the `exiftool.write()` function to write the tags to the file in place using the args `overwrite_original`.
https://photostructure.github.io/exiftool-vendored.js/classes/ExifTool.html#write

```await exiftool.write( imageFile, tags, { writeArgs: ["-overwrite_original"] } );```

I am not sure how I can achieve the same using your library. You only expose one single function for parsing the metadata => `parseMetadata()`

Sorry, I have zero experience with WebAssembly :)

**Comment by boustanihani** [comment]
One more thing, ExifTool is designed to be able to write files to any `pipe`, and the API can be also used to write files to `memory`. So editing Metadata should be possible.

If you expose a new function that returns the edited file content as a BLOB for example, we could then download the file in javascript manually.
Os use something like: https://github.com/eligrey/FileSaver.js

**Comment by vaibhavshirole** [comment]
@boustanihani not sure how far you've gotten the past month, but I just found this repo and threw together a fork with a writeMetadata function to the WebAssembly implementation of ExifTool. Its pretty sloppy (I mainly only write in C) so I may take some time to clean it up. You can probably throw together something better and/or check mine out.
 
Btw, -overwrite_original was giving me issues so I avoided using it. Not going to suggest PR for that reason. 

Thanks for this repo Andrew :)

**Comment by boustanihani** [comment]
Cool, thanks for sharing, I haven't made any progress myself :)

Could you add a usage example for writing metadata to the readme?

**Comment by vaibhavshirole** [comment]
@boustanihani Yes added now. Also there's a link to the project I'm going to be using this for, so in there I have a demo `exiftool-write-test` that you can use to play with this addition to the API. The demo might change a bit though since I'm messing around with this stuff now haha.

**Comment by boustanihani** [comment]
Thanks, I'll take a look at it :)

**Comment by andrewmd5** [comment]
Finished in #9
